config/routes.rb
Rails.application.routes.draw do
  get 'movies/index'
  get 'movies/data', to: 'movies#data'
  post 'movies/load', to: 'movies#load'

  root to: 'movies#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
# frozen_string_literal: true

class Movie < ApplicationRecord
  scope :today_top, lambda { |record_limit|
    where('created_at >= :start_date AND created_at <= :end_date',
          {
            start_date: Time.zone.now.at_beginning_of_day,
            end_date: Time.zone.now.at_end_of_day
          }).order(sessions: :desc).limit(record_limit)
  }

  validates :title, presence: false
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
# frozen_string_literal: true

class MoviesController < ApplicationController
  MOVIES_URL = 'https://rb7.ru/afisha/movies'

  before_action :set_movies, only: %i[index data]

  def index
    if @movies.length.positive?
      redirect_to movies_data_path
    else
      render :index
    end
  end

  def data; end

  def load
    ParsingMoviesWorker.perform_async(MOVIES_URL)
    redirect_to movies_data_path, notice: 'Movies are being uploaded...'
  end

  private

  def set_movies
    @movies = Movie.today_top(3)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/movies_helper.rb
# frozen_string_literal: true

module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestRb7</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/movies/data.html.erb
<h1>TOP 3 Movies</h1>

<% @movies.each do |movie| %>
  <p>
    Title: <%= movie.title %> / Sessions: <%= movie.sessions %>
  </p>
<% end %>

<% if @movies.length.zero? %>
  <%= link_to 'back to main', root_path %>
<% end %>

app/views/movies/index.html.erb
<h1>TOP 3 Movies</h1>

<%= form_tag movies_load_path do %>
  <%= submit_tag 'Load movies' %>
<% end %>